### ISSUE TITLE
Take.

### ISSUE THREAD

**Issue by abelta** [antoinejaussoin/redux-saga-testing#2]
How can you test a saga that "takes" values from an action's payload? That the only example that I haven't found on the documentation.
Example:

```
function* mySaga () => {
  const { payload: data } = yield take(actionName);
  yield put(actionGenerator(data));
}
```

I would like to test if actionGenerator is called and with which params but execution won't even pass to that line because data can't be assigned.

**Comment by antoinejaussoin** [comment]
Hi!

I don't think you can, as `take` is linked to the store.

From the documentation:

> Creates an Effect description that instructs the middleware to wait for a specified action on the Store. The Generator is suspended until an action that matches pattern is dispatched.

However, I think you should separate that logic (the "wait") from the logic that runs when the take yields:

```javascript
import { takeEvery } from 'redux-saga';
import { put, call } from 'redux-saga/effects';
import { INITIALISE } from './state';

export function* onSomeAction(action) {
        const { payload: data } = action;
        yield put(actionGenerator(data));
}

export default function* rootSaga() {
    yield [
        takeEvery(SOME_ACTION, onSomeAction),
        takeEvery(ANOTHER_ACTION, onAnotherAction)
    ];
}
```

Your payload will be in the `action` object that you get from `takeEvery` (I suppose it works the same with `take` if you want).

In general, your sagas containing logic shouldn't interact with the store since you don't have a mock store at that point.

Does it make sense?

**Comment by antoinejaussoin** [comment]
I'll take that as a yes and will close this issue/question
